### ISSUE TITLE
Multiples references to not existing script init_databases.sh

### ISSUE THREAD

**Issue by rmarsollier** [CIRCL/bgp-ranking#5]
Hello, 

The script init_databases.sh does not exist in master, however :

bgp-ranking $ grep -rn init_databases.sh 
./scripts/reinitialize_databases.sh:7:./init_databases.sh
./INSTALL:52:When it is done, start first start_redis.sh, init_databases.sh, start_services.sh and finally start_ranking.sh.

**Comment by Rafiot** [comment]
iirc, init_databases isn't used anymore. I need to check that.
