### ISSUE TITLE
Gateway timeout (504 Gateway Time-out)

### ISSUE THREAD

**Issue by cgi1** [CIRCL/bgp-ranking#6]
[Web request returns 504 Gateway Time-out](http://bgpranking.circl.lu/asn_details?asn=4837) while [csv export is working](http://bgpranking.circl.lu/csv/4837)

<img width="946" alt="grafik" src="https://cloud.githubusercontent.com/assets/18695252/26557447/d1467760-44a1-11e7-997c-b20e0c82c559.png">

**Comment by Rafiot** [comment]
I'll need to restart the webserver, but cannot access to it right now.

**Comment by cgi1** [comment]
@Rafiot: The server seems to be down still. Would you please so kind to check it?

Best!

**Comment by Rafiot** [comment]
Sorry, I was in holiday and then moved. 

Server restarted, it seems to work now
